package org.ks.sys.po;

import java.io.Serializable;

public class TblAuthMenuRel implements Serializable {
    /**
     * 权限id
     * tbl_auth_menu_rel.auth_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    private Long authId;

    /**
     * 菜单id
     * tbl_auth_menu_rel.menu_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    private Long menuId;

    /**
     * tbl_auth_menu_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * 权限id
     * tbl_auth_menu_rel.auth_id
     *
     * @return the value of tbl_auth_menu_rel.auth_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public Long getAuthId() {
        return authId;
    }

    /**
     * 权限id
     * tbl_auth_menu_rel.auth_id
     *
     * @param authId the value for tbl_auth_menu_rel.auth_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public void setAuthId(Long authId) {
        this.authId = authId;
    }

    /**
     * 菜单id
     * tbl_auth_menu_rel.menu_id
     *
     * @return the value of tbl_auth_menu_rel.menu_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * 菜单id
     * tbl_auth_menu_rel.menu_id
     *
     * @param menuId the value for tbl_auth_menu_rel.menu_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_menu_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", authId=").append(authId);
        sb.append(", menuId=").append(menuId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}