package org.ks.sys.po;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TblApprovaCustInfoExample implements Serializable {
    /**
     * tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    protected String orderByClause;

    /**
     * tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    protected boolean distinct;

    /**
     * tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    public TblApprovaCustInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPersionIdIsNull() {
            addCriterion("persion_id is null");
            return (Criteria) this;
        }

        public Criteria andPersionIdIsNotNull() {
            addCriterion("persion_id is not null");
            return (Criteria) this;
        }

        public Criteria andPersionIdEqualTo(Long value) {
            addCriterion("persion_id =", value, "persionId");
            return (Criteria) this;
        }

        public Criteria andPersionIdNotEqualTo(Long value) {
            addCriterion("persion_id <>", value, "persionId");
            return (Criteria) this;
        }

        public Criteria andPersionIdGreaterThan(Long value) {
            addCriterion("persion_id >", value, "persionId");
            return (Criteria) this;
        }

        public Criteria andPersionIdGreaterThanOrEqualTo(Long value) {
            addCriterion("persion_id >=", value, "persionId");
            return (Criteria) this;
        }

        public Criteria andPersionIdLessThan(Long value) {
            addCriterion("persion_id <", value, "persionId");
            return (Criteria) this;
        }

        public Criteria andPersionIdLessThanOrEqualTo(Long value) {
            addCriterion("persion_id <=", value, "persionId");
            return (Criteria) this;
        }

        public Criteria andPersionIdIn(List<Long> values) {
            addCriterion("persion_id in", values, "persionId");
            return (Criteria) this;
        }

        public Criteria andPersionIdNotIn(List<Long> values) {
            addCriterion("persion_id not in", values, "persionId");
            return (Criteria) this;
        }

        public Criteria andPersionIdBetween(Long value1, Long value2) {
            addCriterion("persion_id between", value1, value2, "persionId");
            return (Criteria) this;
        }

        public Criteria andPersionIdNotBetween(Long value1, Long value2) {
            addCriterion("persion_id not between", value1, value2, "persionId");
            return (Criteria) this;
        }

        public Criteria andPersionNameIsNull() {
            addCriterion("persion_name is null");
            return (Criteria) this;
        }

        public Criteria andPersionNameIsNotNull() {
            addCriterion("persion_name is not null");
            return (Criteria) this;
        }

        public Criteria andPersionNameEqualTo(String value) {
            addCriterion("persion_name =", value, "persionName");
            return (Criteria) this;
        }

        public Criteria andPersionNameNotEqualTo(String value) {
            addCriterion("persion_name <>", value, "persionName");
            return (Criteria) this;
        }

        public Criteria andPersionNameGreaterThan(String value) {
            addCriterion("persion_name >", value, "persionName");
            return (Criteria) this;
        }

        public Criteria andPersionNameGreaterThanOrEqualTo(String value) {
            addCriterion("persion_name >=", value, "persionName");
            return (Criteria) this;
        }

        public Criteria andPersionNameLessThan(String value) {
            addCriterion("persion_name <", value, "persionName");
            return (Criteria) this;
        }

        public Criteria andPersionNameLessThanOrEqualTo(String value) {
            addCriterion("persion_name <=", value, "persionName");
            return (Criteria) this;
        }

        public Criteria andPersionNameLike(String value) {
            addCriterion("persion_name like", value, "persionName");
            return (Criteria) this;
        }

        public Criteria andPersionNameNotLike(String value) {
            addCriterion("persion_name not like", value, "persionName");
            return (Criteria) this;
        }

        public Criteria andPersionNameIn(List<String> values) {
            addCriterion("persion_name in", values, "persionName");
            return (Criteria) this;
        }

        public Criteria andPersionNameNotIn(List<String> values) {
            addCriterion("persion_name not in", values, "persionName");
            return (Criteria) this;
        }

        public Criteria andPersionNameBetween(String value1, String value2) {
            addCriterion("persion_name between", value1, value2, "persionName");
            return (Criteria) this;
        }

        public Criteria andPersionNameNotBetween(String value1, String value2) {
            addCriterion("persion_name not between", value1, value2, "persionName");
            return (Criteria) this;
        }

        public Criteria andOpenIdIsNull() {
            addCriterion("open_id is null");
            return (Criteria) this;
        }

        public Criteria andOpenIdIsNotNull() {
            addCriterion("open_id is not null");
            return (Criteria) this;
        }

        public Criteria andOpenIdEqualTo(String value) {
            addCriterion("open_id =", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotEqualTo(String value) {
            addCriterion("open_id <>", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdGreaterThan(String value) {
            addCriterion("open_id >", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdGreaterThanOrEqualTo(String value) {
            addCriterion("open_id >=", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLessThan(String value) {
            addCriterion("open_id <", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLessThanOrEqualTo(String value) {
            addCriterion("open_id <=", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLike(String value) {
            addCriterion("open_id like", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotLike(String value) {
            addCriterion("open_id not like", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdIn(List<String> values) {
            addCriterion("open_id in", values, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotIn(List<String> values) {
            addCriterion("open_id not in", values, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdBetween(String value1, String value2) {
            addCriterion("open_id between", value1, value2, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotBetween(String value1, String value2) {
            addCriterion("open_id not between", value1, value2, "openId");
            return (Criteria) this;
        }

        public Criteria andCerdNoIsNull() {
            addCriterion("cerd_no is null");
            return (Criteria) this;
        }

        public Criteria andCerdNoIsNotNull() {
            addCriterion("cerd_no is not null");
            return (Criteria) this;
        }

        public Criteria andCerdNoEqualTo(String value) {
            addCriterion("cerd_no =", value, "cerdNo");
            return (Criteria) this;
        }

        public Criteria andCerdNoNotEqualTo(String value) {
            addCriterion("cerd_no <>", value, "cerdNo");
            return (Criteria) this;
        }

        public Criteria andCerdNoGreaterThan(String value) {
            addCriterion("cerd_no >", value, "cerdNo");
            return (Criteria) this;
        }

        public Criteria andCerdNoGreaterThanOrEqualTo(String value) {
            addCriterion("cerd_no >=", value, "cerdNo");
            return (Criteria) this;
        }

        public Criteria andCerdNoLessThan(String value) {
            addCriterion("cerd_no <", value, "cerdNo");
            return (Criteria) this;
        }

        public Criteria andCerdNoLessThanOrEqualTo(String value) {
            addCriterion("cerd_no <=", value, "cerdNo");
            return (Criteria) this;
        }

        public Criteria andCerdNoLike(String value) {
            addCriterion("cerd_no like", value, "cerdNo");
            return (Criteria) this;
        }

        public Criteria andCerdNoNotLike(String value) {
            addCriterion("cerd_no not like", value, "cerdNo");
            return (Criteria) this;
        }

        public Criteria andCerdNoIn(List<String> values) {
            addCriterion("cerd_no in", values, "cerdNo");
            return (Criteria) this;
        }

        public Criteria andCerdNoNotIn(List<String> values) {
            addCriterion("cerd_no not in", values, "cerdNo");
            return (Criteria) this;
        }

        public Criteria andCerdNoBetween(String value1, String value2) {
            addCriterion("cerd_no between", value1, value2, "cerdNo");
            return (Criteria) this;
        }

        public Criteria andCerdNoNotBetween(String value1, String value2) {
            addCriterion("cerd_no not between", value1, value2, "cerdNo");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNull() {
            addCriterion("card_no is null");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNotNull() {
            addCriterion("card_no is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoEqualTo(String value) {
            addCriterion("card_no =", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotEqualTo(String value) {
            addCriterion("card_no <>", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThan(String value) {
            addCriterion("card_no >", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("card_no >=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThan(String value) {
            addCriterion("card_no <", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThanOrEqualTo(String value) {
            addCriterion("card_no <=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLike(String value) {
            addCriterion("card_no like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotLike(String value) {
            addCriterion("card_no not like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoIn(List<String> values) {
            addCriterion("card_no in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotIn(List<String> values) {
            addCriterion("card_no not in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoBetween(String value1, String value2) {
            addCriterion("card_no between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotBetween(String value1, String value2) {
            addCriterion("card_no not between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardBankIsNull() {
            addCriterion("card_bank is null");
            return (Criteria) this;
        }

        public Criteria andCardBankIsNotNull() {
            addCriterion("card_bank is not null");
            return (Criteria) this;
        }

        public Criteria andCardBankEqualTo(String value) {
            addCriterion("card_bank =", value, "cardBank");
            return (Criteria) this;
        }

        public Criteria andCardBankNotEqualTo(String value) {
            addCriterion("card_bank <>", value, "cardBank");
            return (Criteria) this;
        }

        public Criteria andCardBankGreaterThan(String value) {
            addCriterion("card_bank >", value, "cardBank");
            return (Criteria) this;
        }

        public Criteria andCardBankGreaterThanOrEqualTo(String value) {
            addCriterion("card_bank >=", value, "cardBank");
            return (Criteria) this;
        }

        public Criteria andCardBankLessThan(String value) {
            addCriterion("card_bank <", value, "cardBank");
            return (Criteria) this;
        }

        public Criteria andCardBankLessThanOrEqualTo(String value) {
            addCriterion("card_bank <=", value, "cardBank");
            return (Criteria) this;
        }

        public Criteria andCardBankLike(String value) {
            addCriterion("card_bank like", value, "cardBank");
            return (Criteria) this;
        }

        public Criteria andCardBankNotLike(String value) {
            addCriterion("card_bank not like", value, "cardBank");
            return (Criteria) this;
        }

        public Criteria andCardBankIn(List<String> values) {
            addCriterion("card_bank in", values, "cardBank");
            return (Criteria) this;
        }

        public Criteria andCardBankNotIn(List<String> values) {
            addCriterion("card_bank not in", values, "cardBank");
            return (Criteria) this;
        }

        public Criteria andCardBankBetween(String value1, String value2) {
            addCriterion("card_bank between", value1, value2, "cardBank");
            return (Criteria) this;
        }

        public Criteria andCardBankNotBetween(String value1, String value2) {
            addCriterion("card_bank not between", value1, value2, "cardBank");
            return (Criteria) this;
        }

        public Criteria andJwIdIsNull() {
            addCriterion("jw_id is null");
            return (Criteria) this;
        }

        public Criteria andJwIdIsNotNull() {
            addCriterion("jw_id is not null");
            return (Criteria) this;
        }

        public Criteria andJwIdEqualTo(String value) {
            addCriterion("jw_id =", value, "jwId");
            return (Criteria) this;
        }

        public Criteria andJwIdNotEqualTo(String value) {
            addCriterion("jw_id <>", value, "jwId");
            return (Criteria) this;
        }

        public Criteria andJwIdGreaterThan(String value) {
            addCriterion("jw_id >", value, "jwId");
            return (Criteria) this;
        }

        public Criteria andJwIdGreaterThanOrEqualTo(String value) {
            addCriterion("jw_id >=", value, "jwId");
            return (Criteria) this;
        }

        public Criteria andJwIdLessThan(String value) {
            addCriterion("jw_id <", value, "jwId");
            return (Criteria) this;
        }

        public Criteria andJwIdLessThanOrEqualTo(String value) {
            addCriterion("jw_id <=", value, "jwId");
            return (Criteria) this;
        }

        public Criteria andJwIdLike(String value) {
            addCriterion("jw_id like", value, "jwId");
            return (Criteria) this;
        }

        public Criteria andJwIdNotLike(String value) {
            addCriterion("jw_id not like", value, "jwId");
            return (Criteria) this;
        }

        public Criteria andJwIdIn(List<String> values) {
            addCriterion("jw_id in", values, "jwId");
            return (Criteria) this;
        }

        public Criteria andJwIdNotIn(List<String> values) {
            addCriterion("jw_id not in", values, "jwId");
            return (Criteria) this;
        }

        public Criteria andJwIdBetween(String value1, String value2) {
            addCriterion("jw_id between", value1, value2, "jwId");
            return (Criteria) this;
        }

        public Criteria andJwIdNotBetween(String value1, String value2) {
            addCriterion("jw_id not between", value1, value2, "jwId");
            return (Criteria) this;
        }

        public Criteria andUseFlagIsNull() {
            addCriterion("use_flag is null");
            return (Criteria) this;
        }

        public Criteria andUseFlagIsNotNull() {
            addCriterion("use_flag is not null");
            return (Criteria) this;
        }

        public Criteria andUseFlagEqualTo(Integer value) {
            addCriterion("use_flag =", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagNotEqualTo(Integer value) {
            addCriterion("use_flag <>", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagGreaterThan(Integer value) {
            addCriterion("use_flag >", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("use_flag >=", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagLessThan(Integer value) {
            addCriterion("use_flag <", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagLessThanOrEqualTo(Integer value) {
            addCriterion("use_flag <=", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagIn(List<Integer> values) {
            addCriterion("use_flag in", values, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagNotIn(List<Integer> values) {
            addCriterion("use_flag not in", values, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagBetween(Integer value1, Integer value2) {
            addCriterion("use_flag between", value1, value2, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("use_flag not between", value1, value2, "useFlag");
            return (Criteria) this;
        }

        public Criteria andCreateAcctIsNull() {
            addCriterion("create_acct is null");
            return (Criteria) this;
        }

        public Criteria andCreateAcctIsNotNull() {
            addCriterion("create_acct is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAcctEqualTo(String value) {
            addCriterion("create_acct =", value, "createAcct");
            return (Criteria) this;
        }

        public Criteria andCreateAcctNotEqualTo(String value) {
            addCriterion("create_acct <>", value, "createAcct");
            return (Criteria) this;
        }

        public Criteria andCreateAcctGreaterThan(String value) {
            addCriterion("create_acct >", value, "createAcct");
            return (Criteria) this;
        }

        public Criteria andCreateAcctGreaterThanOrEqualTo(String value) {
            addCriterion("create_acct >=", value, "createAcct");
            return (Criteria) this;
        }

        public Criteria andCreateAcctLessThan(String value) {
            addCriterion("create_acct <", value, "createAcct");
            return (Criteria) this;
        }

        public Criteria andCreateAcctLessThanOrEqualTo(String value) {
            addCriterion("create_acct <=", value, "createAcct");
            return (Criteria) this;
        }

        public Criteria andCreateAcctLike(String value) {
            addCriterion("create_acct like", value, "createAcct");
            return (Criteria) this;
        }

        public Criteria andCreateAcctNotLike(String value) {
            addCriterion("create_acct not like", value, "createAcct");
            return (Criteria) this;
        }

        public Criteria andCreateAcctIn(List<String> values) {
            addCriterion("create_acct in", values, "createAcct");
            return (Criteria) this;
        }

        public Criteria andCreateAcctNotIn(List<String> values) {
            addCriterion("create_acct not in", values, "createAcct");
            return (Criteria) this;
        }

        public Criteria andCreateAcctBetween(String value1, String value2) {
            addCriterion("create_acct between", value1, value2, "createAcct");
            return (Criteria) this;
        }

        public Criteria andCreateAcctNotBetween(String value1, String value2) {
            addCriterion("create_acct not between", value1, value2, "createAcct");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateAcctIsNull() {
            addCriterion("update_acct is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAcctIsNotNull() {
            addCriterion("update_acct is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAcctEqualTo(String value) {
            addCriterion("update_acct =", value, "updateAcct");
            return (Criteria) this;
        }

        public Criteria andUpdateAcctNotEqualTo(String value) {
            addCriterion("update_acct <>", value, "updateAcct");
            return (Criteria) this;
        }

        public Criteria andUpdateAcctGreaterThan(String value) {
            addCriterion("update_acct >", value, "updateAcct");
            return (Criteria) this;
        }

        public Criteria andUpdateAcctGreaterThanOrEqualTo(String value) {
            addCriterion("update_acct >=", value, "updateAcct");
            return (Criteria) this;
        }

        public Criteria andUpdateAcctLessThan(String value) {
            addCriterion("update_acct <", value, "updateAcct");
            return (Criteria) this;
        }

        public Criteria andUpdateAcctLessThanOrEqualTo(String value) {
            addCriterion("update_acct <=", value, "updateAcct");
            return (Criteria) this;
        }

        public Criteria andUpdateAcctLike(String value) {
            addCriterion("update_acct like", value, "updateAcct");
            return (Criteria) this;
        }

        public Criteria andUpdateAcctNotLike(String value) {
            addCriterion("update_acct not like", value, "updateAcct");
            return (Criteria) this;
        }

        public Criteria andUpdateAcctIn(List<String> values) {
            addCriterion("update_acct in", values, "updateAcct");
            return (Criteria) this;
        }

        public Criteria andUpdateAcctNotIn(List<String> values) {
            addCriterion("update_acct not in", values, "updateAcct");
            return (Criteria) this;
        }

        public Criteria andUpdateAcctBetween(String value1, String value2) {
            addCriterion("update_acct between", value1, value2, "updateAcct");
            return (Criteria) this;
        }

        public Criteria andUpdateAcctNotBetween(String value1, String value2) {
            addCriterion("update_acct not between", value1, value2, "updateAcct");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_approva_cust_info
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 21 10:19:24 CST 2020
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_approva_cust_info
     *
     * @mbg.generated Mon Sep 21 10:19:24 CST 2020
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}