package org.ks.sys.po;

import java.io.Serializable;

public class TblAuthFileRel implements Serializable {
    /**
     * 权限id
     * tbl_auth_file_rel.auth_id
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    private Long authId;

    /**
     * 附件类型id
     * tbl_auth_file_rel.file_type_id
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    private Long fileTypeId;

    /**
     * tbl_auth_file_rel
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * 权限id
     * tbl_auth_file_rel.auth_id
     *
     * @return the value of tbl_auth_file_rel.auth_id
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    public Long getAuthId() {
        return authId;
    }

    /**
     * 权限id
     * tbl_auth_file_rel.auth_id
     *
     * @param authId the value for tbl_auth_file_rel.auth_id
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    public void setAuthId(Long authId) {
        this.authId = authId;
    }

    /**
     * 附件类型id
     * tbl_auth_file_rel.file_type_id
     *
     * @return the value of tbl_auth_file_rel.file_type_id
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    public Long getFileTypeId() {
        return fileTypeId;
    }

    /**
     * 附件类型id
     * tbl_auth_file_rel.file_type_id
     *
     * @param fileTypeId the value for tbl_auth_file_rel.file_type_id
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    public void setFileTypeId(Long fileTypeId) {
        this.fileTypeId = fileTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_file_rel
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", authId=").append(authId);
        sb.append(", fileTypeId=").append(fileTypeId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}