package org.ks.sys.po;

import java.io.Serializable;

public class TblGroupRoleRel implements Serializable {
    /**
     * 用户组id
     * tbl_group_role_rel.group_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    private Long groupId;

    /**
     * 角色id
     * tbl_group_role_rel.role_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    private Long roleId;

    /**
     * tbl_group_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * 用户组id
     * tbl_group_role_rel.group_id
     *
     * @return the value of tbl_group_role_rel.group_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * 用户组id
     * tbl_group_role_rel.group_id
     *
     * @param groupId the value for tbl_group_role_rel.group_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * 角色id
     * tbl_group_role_rel.role_id
     *
     * @return the value of tbl_group_role_rel.role_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * 角色id
     * tbl_group_role_rel.role_id
     *
     * @param roleId the value for tbl_group_role_rel.role_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupId=").append(groupId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}