package org.ks.sys.po;

import java.io.Serializable;

public class TblRoleAuthRel implements Serializable {
    /**
     * 角色id
     * tbl_role_auth_rel.role_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    private Long roleId;

    /**
     * 权限id
     * tbl_role_auth_rel.auth_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    private Long authId;

    /**
     * tbl_role_auth_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * 角色id
     * tbl_role_auth_rel.role_id
     *
     * @return the value of tbl_role_auth_rel.role_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * 角色id
     * tbl_role_auth_rel.role_id
     *
     * @param roleId the value for tbl_role_auth_rel.role_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * 权限id
     * tbl_role_auth_rel.auth_id
     *
     * @return the value of tbl_role_auth_rel.auth_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public Long getAuthId() {
        return authId;
    }

    /**
     * 权限id
     * tbl_role_auth_rel.auth_id
     *
     * @param authId the value for tbl_role_auth_rel.auth_id
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public void setAuthId(Long authId) {
        this.authId = authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_auth_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", authId=").append(authId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}