package org.ks.sys.po;

import java.io.Serializable;

public class TblSysInfo implements Serializable {
    /**
     * tbl_sys_info.sys_code
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    private String sysCode;

    /**
     * tbl_sys_info.sys_name
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    private String sysName;

    /**
     * tbl_sys_info
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * tbl_sys_info.sys_code
     *
     * @return the value of tbl_sys_info.sys_code
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public String getSysCode() {
        return sysCode;
    }

    /**
     * tbl_sys_info.sys_code
     *
     * @param sysCode the value for tbl_sys_info.sys_code
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public void setSysCode(String sysCode) {
        this.sysCode = sysCode;
    }

    /**
     * tbl_sys_info.sys_name
     *
     * @return the value of tbl_sys_info.sys_name
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * tbl_sys_info.sys_name
     *
     * @param sysName the value for tbl_sys_info.sys_name
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    public void setSysName(String sysName) {
        this.sysName = sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_info
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysCode=").append(sysCode);
        sb.append(", sysName=").append(sysName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}