package org.ks.sys.joblog.bean;

import java.io.Serializable;
import java.util.Date;

public class Joblog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblog.jid
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    private Integer jid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblog.jobtype
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    private String jobtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblog.starttime
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblog.endtime
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblog.total
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblog.succupdate
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    private Integer succupdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblog.succinstart
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    private Integer succinstart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblog.exception
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    private String exception;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table joblog
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblog.jid
     *
     * @return the value of joblog.jid
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public Integer getJid() {
        return jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblog.jid
     *
     * @param jid the value for joblog.jid
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public void setJid(Integer jid) {
        this.jid = jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblog.jobtype
     *
     * @return the value of joblog.jobtype
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public String getJobtype() {
        return jobtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblog.jobtype
     *
     * @param jobtype the value for joblog.jobtype
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public void setJobtype(String jobtype) {
        this.jobtype = jobtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblog.starttime
     *
     * @return the value of joblog.starttime
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblog.starttime
     *
     * @param starttime the value for joblog.starttime
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblog.endtime
     *
     * @return the value of joblog.endtime
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblog.endtime
     *
     * @param endtime the value for joblog.endtime
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblog.total
     *
     * @return the value of joblog.total
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblog.total
     *
     * @param total the value for joblog.total
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblog.succupdate
     *
     * @return the value of joblog.succupdate
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public Integer getSuccupdate() {
        return succupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblog.succupdate
     *
     * @param succupdate the value for joblog.succupdate
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public void setSuccupdate(Integer succupdate) {
        this.succupdate = succupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblog.succinstart
     *
     * @return the value of joblog.succinstart
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public Integer getSuccinstart() {
        return succinstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblog.succinstart
     *
     * @param succinstart the value for joblog.succinstart
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public void setSuccinstart(Integer succinstart) {
        this.succinstart = succinstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblog.exception
     *
     * @return the value of joblog.exception
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public String getException() {
        return exception;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblog.exception
     *
     * @param exception the value for joblog.exception
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    public void setException(String exception) {
        this.exception = exception;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblog
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jid=").append(jid);
        sb.append(", jobtype=").append(jobtype);
        sb.append(", starttime=").append(starttime);
        sb.append(", endtime=").append(endtime);
        sb.append(", total=").append(total);
        sb.append(", succupdate=").append(succupdate);
        sb.append(", succinstart=").append(succinstart);
        sb.append(", exception=").append(exception);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}