logStash:
  url: 10.20.23.2:5044
nacos:
  service-address: 10.20.23.4
  port: 8848
  namespace: dev
logging:
  config: classpath:logback-logstash.xml
  info-file: ./${spring.application.name}-info.log
  error-file: ./${spring.application.name}-error.log
server:
  port: 8080
  servlet:
    context-path: /view
spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: ${nacos.service-address}:${nacos.port}
        namespace: ${nacos.namespace}
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
  jackson:
    generator:
      write_numbers_as_strings: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
    suffix: .html
    enabled: true
  application:
    name: view
  activiti:
    check-process-definitions: false
  datasource:
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: XcodeV1V
        allow: ""
      basic-write:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.20.16.5:3306/common?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false&autoReconnect=true&failOverReadOnly=false
        username: common
        password: iphonex5555

        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 5
        maxActive: 200
        maxWait: 6000
        timeBetweenEvictionRunsMillis: 6000
        minEvictableIdleTimeMillis: 30000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false

        #        removeAbandoned: true

        #        remove-abandoned-timeout: 180

        #filters: stat,wall,log4j
        maxPoolPreparedStatementPerConnectionSize: 20
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=100
        #useGlobalDataSourceStat: true
        query-timeout: 600
        time-between-log-stats-millis: 300000

      basic-read:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.20.16.6:3306/common?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false&autoReconnect=true&failOverReadOnly=false
        username: common
        password: iphonex5555

        type: com.alibaba.druid.pool.DruidDataSource

        initialSize: 5
        #
        minIdle: 5
        #
        maxActive: 200

        maxWait: 60000

        timeBetweenEvictionRunsMillis: 60000

        minEvictableIdleTimeMillis: 300000

        validationQuery: SELECT 1

        testWhileIdle: true

        testOnBorrow: false

        testOnReturn: false

        #        removeAbandoned: true

        #        remove-abandoned-timeout: 180

        #filters: stat,wall,log4j
        maxPoolPreparedStatementPerConnectionSize: 20
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        #useGlobalDataSourceStat: true
        query-timeout: 6000
        time-between-log-stats-millis: 300000
  redis:
    host: 10.20.23.3
    port: 6379
    password: eagle
    database: 1
    timeout: 60s
    jedis:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 10
        min-idle: 2

mybatis:
  configuration:
    map-underscore-to-camel-case: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    nacos-discovery:
      enabled: true
    health:
      show-details: always
  server:
    servlet:
      context-path: ${server.servlet.context-path}/actuator