server:
  port: 8080
  servlet:
    context-path: /ksview
spring:
  application: /ksview
  datasource:
    process:
      #dataSource Pool configuration
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.20.16.24:3306/kswechat?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: qwe.123
      initialSize: 5
      minIdle: 5
      maxActive: 80
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      #exceptionSorter: false
      #      testOnReturn: false
      #      poolPreparedStatements: true
      #      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      useGlobalDataSourceStat: true
  redis:
    host: 10.10.80.51
    port: 6379
    password: ccrs
    database: 11
    timeout: 60s
    jedis:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 10
        min-idle: 2
lxy:
  addr: http://10.20.20.6
  user: application
  pwd: qaz123
  pathType: ent

#联想云上传路径 手动 自动
manualOperationPath: /Application/1.153/G/filepdf/
voluntarilyPath: /Application/1.153/G/voluntarilyfile/

#服务器附件手动存放路径
winfilePath: E:/file/template/
linuxfilePath: /home/ks/local/file/template/

#服件自动上传路径
winvoluntarilyPath: E:/file/voluntarilytemplate/
linuxvoluntarilyPath: /home/ks/local/file/voluntarilytemplate/

#SFTP的地址账号密码
SFTP:
  host: 103.28.213.146
  username: cqdb
  password: cqdbzaq1!@
  port: 22
  path: /upload/ipload/