server:
  port: 8080
  servlet:
    context-path: /ksview
spring:
  application: /ksview
  datasource:
    process:
      #dataSource Pool configuration
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.10.1.231:3306/ceshi?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: qaz123
      initialSize: 5
      minIdle: 5
      maxActive: 80
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      #exceptionSorter: false
      #      testOnReturn: false
      #      poolPreparedStatements: true
      #      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      useGlobalDataSourceStat: true
  redis:
    host: 10.10.80.51
    port: 6379
    password: ccrs
    database: 11
    timeout: 60s
    jedis:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 10
        min-idle: 2


#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    nacos-discovery:
#      enabled: true
#    health:
#      show-details: always
#  server:
#    servlet:
#      context-path: ${server.servlet.context-path}/actuator




