package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblAuthFileRel;
import org.ks.sys.po.TblAuthFileRelExample;

public interface TblAuthFileRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_file_rel
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    long countByExample(TblAuthFileRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_file_rel
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    int deleteByExample(TblAuthFileRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_file_rel
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    int insert(TblAuthFileRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_file_rel
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    int insertSelective(TblAuthFileRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_file_rel
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    List<TblAuthFileRel> selectByExample(TblAuthFileRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_file_rel
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblAuthFileRel record, @Param("example") TblAuthFileRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_file_rel
     *
     * @mbg.generated Thu May 21 17:17:28 CST 2020
     */
    int updateByExample(@Param("record") TblAuthFileRel record, @Param("example") TblAuthFileRelExample example);
}