package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblApprovaFileInfo;
import org.ks.sys.po.TblApprovaFileInfoExample;

public interface TblApprovaFileInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_file_info
     *
     * @mbg.generated Thu Nov 19 15:58:49 CST 2020
     */
    long countByExample(TblApprovaFileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_file_info
     *
     * @mbg.generated Thu Nov 19 15:58:49 CST 2020
     */
    int deleteByExample(TblApprovaFileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_file_info
     *
     * @mbg.generated Thu Nov 19 15:58:49 CST 2020
     */
    int deleteByPrimaryKey(Long fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_file_info
     *
     * @mbg.generated Thu Nov 19 15:58:49 CST 2020
     */
    int insert(TblApprovaFileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_file_info
     *
     * @mbg.generated Thu Nov 19 15:58:49 CST 2020
     */
    int insertSelective(TblApprovaFileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_file_info
     *
     * @mbg.generated Thu Nov 19 15:58:49 CST 2020
     */
    List<TblApprovaFileInfo> selectByExample(TblApprovaFileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_file_info
     *
     * @mbg.generated Thu Nov 19 15:58:49 CST 2020
     */
    TblApprovaFileInfo selectByPrimaryKey(Long fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_file_info
     *
     * @mbg.generated Thu Nov 19 15:58:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblApprovaFileInfo record, @Param("example") TblApprovaFileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_file_info
     *
     * @mbg.generated Thu Nov 19 15:58:49 CST 2020
     */
    int updateByExample(@Param("record") TblApprovaFileInfo record, @Param("example") TblApprovaFileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_file_info
     *
     * @mbg.generated Thu Nov 19 15:58:49 CST 2020
     */
    int updateByPrimaryKeySelective(TblApprovaFileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_approva_file_info
     *
     * @mbg.generated Thu Nov 19 15:58:49 CST 2020
     */
    int updateByPrimaryKey(TblApprovaFileInfo record);
}