package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblAuthMenuRel;
import org.ks.sys.po.TblAuthMenuRelExample;

public interface TblAuthMenuRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_menu_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    long countByExample(TblAuthMenuRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_menu_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int deleteByExample(TblAuthMenuRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_menu_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insert(TblAuthMenuRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_menu_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insertSelective(TblAuthMenuRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_menu_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    List<TblAuthMenuRel> selectByExample(TblAuthMenuRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_menu_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblAuthMenuRel record, @Param("example") TblAuthMenuRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_menu_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExample(@Param("record") TblAuthMenuRel record, @Param("example") TblAuthMenuRelExample example);
}