package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblAuth;
import org.ks.sys.po.TblAuthExample;

public interface TblAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    long countByExample(TblAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int deleteByExample(TblAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int deleteByPrimaryKey(Long authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int insert(TblAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int insertSelective(TblAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    List<TblAuth> selectByExample(TblAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    TblAuth selectByPrimaryKey(Long authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblAuth record, @Param("example") TblAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int updateByExample(@Param("record") TblAuth record, @Param("example") TblAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int updateByPrimaryKeySelective(TblAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int updateByPrimaryKey(TblAuth record);
}