package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblCtrlUserInfo;
import org.ks.sys.po.TblCtrlUserInfoExample;

public interface TblCtrlUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ctrl_user_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    long countByExample(TblCtrlUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ctrl_user_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int deleteByExample(TblCtrlUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ctrl_user_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int deleteByPrimaryKey(Long ctrlUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ctrl_user_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int insert(TblCtrlUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ctrl_user_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int insertSelective(TblCtrlUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ctrl_user_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    List<TblCtrlUserInfo> selectByExample(TblCtrlUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ctrl_user_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    TblCtrlUserInfo selectByPrimaryKey(Long ctrlUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ctrl_user_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblCtrlUserInfo record, @Param("example") TblCtrlUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ctrl_user_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int updateByExample(@Param("record") TblCtrlUserInfo record, @Param("example") TblCtrlUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ctrl_user_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int updateByPrimaryKeySelective(TblCtrlUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ctrl_user_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int updateByPrimaryKey(TblCtrlUserInfo record);
}