package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblGroupRoleRel;
import org.ks.sys.po.TblGroupRoleRelExample;

public interface TblGroupRoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    long countByExample(TblGroupRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int deleteByExample(TblGroupRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insert(TblGroupRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insertSelective(TblGroupRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    List<TblGroupRoleRel> selectByExample(TblGroupRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblGroupRoleRel record, @Param("example") TblGroupRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExample(@Param("record") TblGroupRoleRel record, @Param("example") TblGroupRoleRelExample example);
}