package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblGroup;
import org.ks.sys.po.TblGroupExample;

public interface TblGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    long countByExample(TblGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int deleteByExample(TblGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int deleteByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insert(TblGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insertSelective(TblGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    List<TblGroup> selectByExample(TblGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    TblGroup selectByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblGroup record, @Param("example") TblGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExample(@Param("record") TblGroup record, @Param("example") TblGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByPrimaryKeySelective(TblGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByPrimaryKey(TblGroup record);
}