package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblIpInfo;
import org.ks.sys.po.TblIpInfoExample;

public interface TblIpInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ip_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    long countByExample(TblIpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ip_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int deleteByExample(TblIpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ip_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int deleteByPrimaryKey(Long iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ip_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int insert(TblIpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ip_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int insertSelective(TblIpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ip_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    List<TblIpInfo> selectByExample(TblIpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ip_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    TblIpInfo selectByPrimaryKey(Long iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ip_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblIpInfo record, @Param("example") TblIpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ip_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int updateByExample(@Param("record") TblIpInfo record, @Param("example") TblIpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ip_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int updateByPrimaryKeySelective(TblIpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ip_info
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int updateByPrimaryKey(TblIpInfo record);
}