package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblOrgRoleRel;
import org.ks.sys.po.TblOrgRoleRelExample;

public interface TblOrgRoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    long countByExample(TblOrgRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int deleteByExample(TblOrgRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insert(TblOrgRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insertSelective(TblOrgRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    List<TblOrgRoleRel> selectByExample(TblOrgRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblOrgRoleRel record, @Param("example") TblOrgRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org_role_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExample(@Param("record") TblOrgRoleRel record, @Param("example") TblOrgRoleRelExample example);
}