package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblOrgExample;
import org.ks.sys.po.TblOrg;

public interface TblOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org
     *
     * @mbg.generated Mon May 11 19:18:45 CST 2020
     */
    long countByExample(TblOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org
     *
     * @mbg.generated Mon May 11 19:18:45 CST 2020
     */
    int deleteByExample(TblOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org
     *
     * @mbg.generated Mon May 11 19:18:45 CST 2020
     */
    int deleteByPrimaryKey(Long orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org
     *
     * @mbg.generated Mon May 11 19:18:45 CST 2020
     */
    int insert(TblOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org
     *
     * @mbg.generated Mon May 11 19:18:45 CST 2020
     */
    int insertSelective(TblOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org
     *
     * @mbg.generated Mon May 11 19:18:45 CST 2020
     */
    List<TblOrg> selectByExample(TblOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org
     *
     * @mbg.generated Mon May 11 19:18:45 CST 2020
     */
    TblOrg selectByPrimaryKey(Long orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org
     *
     * @mbg.generated Mon May 11 19:18:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblOrg record, @Param("example") TblOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org
     *
     * @mbg.generated Mon May 11 19:18:45 CST 2020
     */
    int updateByExample(@Param("record") TblOrg record, @Param("example") TblOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org
     *
     * @mbg.generated Mon May 11 19:18:45 CST 2020
     */
    int updateByPrimaryKeySelective(TblOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_org
     *
     * @mbg.generated Mon May 11 19:18:45 CST 2020
     */
    int updateByPrimaryKey(TblOrg record);
}