package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblRoleExample;
import org.ks.sys.po.TblRole;

public interface TblRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    long countByExample(TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int deleteByExample(TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insert(TblRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insertSelective(TblRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    List<TblRole> selectByExample(TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    TblRole selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblRole record, @Param("example") TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExample(@Param("record") TblRole record, @Param("example") TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByPrimaryKeySelective(TblRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByPrimaryKey(TblRole record);
}