package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblRoleAuthRel;
import org.ks.sys.po.TblRoleAuthRelExample;

public interface TblRoleAuthRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_auth_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    long countByExample(TblRoleAuthRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_auth_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int deleteByExample(TblRoleAuthRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_auth_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insert(TblRoleAuthRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_auth_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insertSelective(TblRoleAuthRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_auth_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    List<TblRoleAuthRel> selectByExample(TblRoleAuthRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_auth_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblRoleAuthRel record, @Param("example") TblRoleAuthRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_auth_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExample(@Param("record") TblRoleAuthRel record, @Param("example") TblRoleAuthRelExample example);
}