package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblSysInfo;
import org.ks.sys.po.TblSysInfoExample;

public interface TblSysInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_info
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    long countByExample(TblSysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_info
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int deleteByExample(TblSysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_info
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insert(TblSysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_info
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insertSelective(TblSysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_info
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    List<TblSysInfo> selectByExample(TblSysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_info
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblSysInfo record, @Param("example") TblSysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_info
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExample(@Param("record") TblSysInfo record, @Param("example") TblSysInfoExample example);
}