package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblUserCtrlRelExample;
import org.ks.sys.po.TblUserCtrlRel;

public interface TblUserCtrlRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_ctrl_rel
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    long countByExample(TblUserCtrlRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_ctrl_rel
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int deleteByExample(TblUserCtrlRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_ctrl_rel
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int insert(TblUserCtrlRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_ctrl_rel
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int insertSelective(TblUserCtrlRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_ctrl_rel
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    List<TblUserCtrlRel> selectByExample(TblUserCtrlRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_ctrl_rel
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblUserCtrlRel record, @Param("example") TblUserCtrlRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_ctrl_rel
     *
     * @mbg.generated Wed Aug 12 17:40:19 CST 2020
     */
    int updateByExample(@Param("record") TblUserCtrlRel record, @Param("example") TblUserCtrlRelExample example);
}