package org.ks.sys.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.po.TblUserOrgRel;
import org.ks.sys.po.TblUserOrgRelExample;

public interface TblUserOrgRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_org_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    long countByExample(TblUserOrgRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_org_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int deleteByExample(TblUserOrgRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_org_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insert(TblUserOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_org_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int insertSelective(TblUserOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_org_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    List<TblUserOrgRel> selectByExample(TblUserOrgRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_org_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblUserOrgRel record, @Param("example") TblUserOrgRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_org_rel
     *
     * @mbg.generated Mon Apr 20 18:14:45 CST 2020
     */
    int updateByExample(@Param("record") TblUserOrgRel record, @Param("example") TblUserOrgRelExample example);
}