package org.ks.sys.declarationuser.service;

import org.apache.ibatis.annotations.Param;
import org.ks.sys.declaration.bean.TblDeclaration;
import org.ks.sys.declaration.vo.ConditionalQueryDecl;
import org.ks.sys.declarationuser.bean.TblDeclarationUser;
import org.ks.sys.declarationuser.bean.TblDeclarationUserExample;
import org.ks.sys.declarationuser.vo.ConditionalQueryDeclUser;

import java.util.List;

/**
 * @author fangshaofeng
 * @date 2022/1/10
 * @apiNote
 */
public interface TblDeclarationUserService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_declaration_user
     *
     * @mbg.generated Thu Jan 06 17:24:53 CST 2022
     */
    long countByExample(TblDeclarationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_declaration_user
     *
     * @mbg.generated Thu Jan 06 17:24:53 CST 2022
     */
    int deleteByExample(TblDeclarationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_declaration_user
     *
     * @mbg.generated Thu Jan 06 17:24:53 CST 2022
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_declaration_user
     *
     * @mbg.generated Thu Jan 06 17:24:53 CST 2022
     */
    int insert(TblDeclarationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_declaration_user
     *
     * @mbg.generated Thu Jan 06 17:24:53 CST 2022
     */
    int insertSelective(TblDeclarationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_declaration_user
     *
     * @mbg.generated Thu Jan 06 17:24:53 CST 2022
     */
    List<TblDeclarationUser> selectByExample(TblDeclarationUserExample example);


    List<TblDeclarationUser> selectByQueryDeclUser(ConditionalQueryDeclUser conditionalQueryDeclUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_declaration_user
     *
     * @mbg.generated Thu Jan 06 17:24:53 CST 2022
     */
    TblDeclarationUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_declaration_user
     *
     * @mbg.generated Thu Jan 06 17:24:53 CST 2022
     */
    int updateByExampleSelective(@Param("record") TblDeclarationUser record, @Param("example") TblDeclarationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_declaration_user
     *
     * @mbg.generated Thu Jan 06 17:24:53 CST 2022
     */
    int updateByExample(@Param("record") TblDeclarationUser record, @Param("example") TblDeclarationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_declaration_user
     *
     * @mbg.generated Thu Jan 06 17:24:53 CST 2022
     */
    int updateByPrimaryKeySelective(TblDeclarationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_declaration_user
     *
     * @mbg.generated Thu Jan 06 17:24:53 CST 2022
     */
    int updateByPrimaryKey(TblDeclarationUser record);
}
