package org.ks.sys.joblog.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ks.sys.joblog.bean.Joblog;
import org.ks.sys.joblog.bean.JoblogExample;

public interface JoblogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblog
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    long countByExample(JoblogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblog
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    int deleteByExample(JoblogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblog
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    int deleteByPrimaryKey(Integer jid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblog
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    int insert(Joblog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblog
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    int insertSelective(Joblog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblog
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    List<Joblog> selectByExample(JoblogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblog
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    Joblog selectByPrimaryKey(Integer jid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblog
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    int updateByExampleSelective(@Param("record") Joblog record, @Param("example") JoblogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblog
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    int updateByExample(@Param("record") Joblog record, @Param("example") JoblogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblog
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    int updateByPrimaryKeySelective(Joblog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblog
     *
     * @mbg.generated Tue Jan 25 10:21:12 CST 2022
     */
    int updateByPrimaryKey(Joblog record);
}